### ISSUE TITLE
Ability to disable jgitver based on a Maven profile

### ISSUE THREAD

**Issue by drekbour** [jgitver/jgitver.github.io#3]
JGitVer does a good job of applying a version so we can meet CD "every commit is releasable" with a _meaningful_ version. 

When in the _IDE_ I don't really want JGitVer rules at _all_ as it means the version keeps changing on every (unpushed) commit! I actually want the original `project.version` from `pom.xml` which is set to 1.0-SNAPSHOT so whatever projects I have open are automatically cross-linked.

### Simple fix (and probably a good idea anyway):

A simple global off-switch to stop jgitver logic: see `-Dversioning.disable=true` flag in https://github.com/qoomon/maven-git-versioning-extension

### Better fix

Thinking out loud here so, if this doesn't make sense, please challenge it!

The usual way to do this sort of thing is via Maven profiles which allow two sets of rules (one for ide IDE and one for CI). Is it possible to support an extra rule:

    <enabledInProfiles>ci,!ide</enabledInProfiles>

using he common pattern of `,` to mean *AND* and `!` to mean *NOT*.

**Comment by drekbour** [comment]
I see this isn't the right project for the issue to be raised in (and `-Djgitver.skip=true` exists!)

**Comment by McFoggy** [comment]
@drekbour also profiles cannot be used because jgitver is a maven extension that is fired/executing before any profile resolution is executed.

And yes I know that qoomon plugin has similarities, they forked from jgitver...
